### ISSUE TITLE
Improved image handling - tracking issue

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar#2325]
There are a lot of tickets at the moment related to image handling, most of which are interrelated. Here's a list of the various issues that I can think of:

- [ ]  Allow per-variant product images (#1611, #1643).
- [ ]  Fix broken image ordering in dashboard (#2289) and improve the image upload generally to be more user friendly.
- [ ]  Allow reordering of images from dashboard (#2287).
- [ ] Figure out a better way to handle the "missing image" image (#2168).
- [ ]  Make it possible for projects to use a different thumbnailing solution (#1408).
- [ ] Allow image attributes (?).
- [ ] Build in support for retina images

There are a few PRs currently open to address some of these, but I think we need to be mindful of the overall aims (e.g., the JS proposed in #2287 is specific to the current dashboard, which is going to change). The dashboard refactor in #2302 will be important to several of these issues.

Broadly I think there are three main tasks:

1. Refactor models to allow better variant support.
2. Refactor dashboard UI for handling images.
3. Move thumbnailing logic into a standalone module that can be overridden. At the same time also add support for retina thumbnails etc.

**Comment by sasha0** [comment]
> Build in support for retina images

@solarissmoke please create a separate issue for that if the todo item is still relevant.

Otherwise, we can close the issue, since other items has been already addressed.

**Comment by specialunderwear** [comment]
closing all issues that are feature requests without open PR's attached.
